name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - master # or master before October 2020

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
            
      - name: Build Jekyll for GitHub Pages
        uses: actions/jekyll-build-pages@v1.0.5
        with:
          # Directory where the source files reside.
          source: ./
          # Output directory of the build. Although it can be nested inside the source, it cannot be the same as the source directory.
          destination: ./_site
          # Publishes posts with a future date. When set to true, the build is made with the --future option which overrides the future option that may be set in a Jekyll configuration file.
          future: true
          # The SHA-1 of the git commit for which the build is running. Default to GITHUB_SHA.
          build_revision:  ${{ github.sha }}
          # Verbose output
          verbose: true
          # GitHub token
          token: ${{ github.token }}
      - name: jekyll-deploy-gh-pages
  # You may pin to the exact commit or the version.
  # uses: BryanSchuetz/jekyll-deploy-gh-pages@c65ae23c7f03c25370004f16cba53110df1a4da4
        uses: BryanSchuetz/jekyll-deploy-gh-pages@v2.0
